#!/usr/bin/awk -f

BEGIN {
  expr_cmd = "./a.out";
}

{
  expr = $1;

  cmd = "/usr/bin/awk " "\"BEGIN { print " expr  ";}\"";
  cmd |getline r1;
  close(cmd);

  cmd = "echo '" expr "' |" expr_cmd;
  cmd |getline r2;
  close(cmd);

  printf expr " => " r1 " : " r2;
  if (r1 == r2) {
    print " OK!";
  } else {
    print " WRONG!";
  }
}
